### ISSUE TITLE
Question: Restarting MagicLan 2 adapters

### ISSUE THREAD

**Issue by seb-koch** [2Fake/devolo_plc_api#41]
Hi,

i stumbled upon this project and hope it may help in my use case. My MagicLan powerlan connection is shaky from time to time which shows in lowered bandwidths. What helps is restarting the device and all things go back to normal. I was searching for an API i could use to restart the device remotely by a script. I briefly searched the projects code but didn't find any API call.
Does devolo_plc_api provide any interface to restart the device? Do you know of any API? I would consider trying to implement it if maybe this is a missing feature?

All the best,
Sebastian

**Comment by 2Fake** [comment]
Hi, 

currently its not possible to restart the device by the API we use. 

If it will be possible in the future we will implement this.

best regards
Markus

**Comment by AlphaDE** [comment]
+1 same issue, same request.

**Comment by AlphaDE** [comment]
@2Fake Good news, thx

**Comment by 2Fake** [comment]
@AlphaDE @seb-koch With the new release the API is able to restart your devices. Probably you'll have to wait until your devices receive a firmware version which announce this feature.
