### ISSUE TITLE
Please add the raw .proto files to the repo

### ISSUE THREAD

**Issue by gebi** [2Fake/devolo_plc_api#99]
There is no point in hiding them with python protobuf, could you please add them?

i'd need to communicate to the devolo powerlan adapters from a different language and it would be a huge timesaver, thx!

**Comment by Shutgun** [comment]
Hi @gebi, they are property of devolo and we don't own any rights on them. I will ask my contacts at devolo, if they can publish them somehow. However, an answer might take a few weeks because of the holiday season.

**Comment by gebi** [comment]
thx for the fast answer!

but you already published them, as the python client can not work without them, like eg. i just asked to not needing to fiddle it out of the code...

```
syntax = "proto3";

package plcnet.api;

option java_package = "plcnet";
option java_outer_classname = "net";

message GetNetworkOverview {
  message Device {
    enum Topology {
      UNKNOWN_TOPOLOGY = 0;
      LOCAL = 1;
      REMOTE = 2;
    }
    enum Technology {
      UNKNOWN_TECHNOLOGY = 0;
      HPAV_THUNDERBOLT = 3;
      HPAV_PANTHER = 4;
      GHN_SPIRIT = 7;
    }
    string product_name = 1;
    string product_id = 2;
    string friendly_version = 3;
    string full_version = 4;
    string user_device_name = 5;
    string user_network_name = 6;
    string mac_address = 7;
    .plcnet.api.GetNetworkOverview.Device.Topology topology = 8;
    .plcnet.api.GetNetworkOverview.Device.Technology technology = 9;
    repeated string bridged_devices = 10;
    string ipv4_address = 11;
    bool attached_to_router = 12;
  }
  message DataRate {
    string mac_address_from = 1;
    string mac_address_to = 2;
    double tx_rate = 3;
    double rx_rate = 4;
  }
  message LogicalNetwork {
    repeated .plcnet.api.GetNetworkOverview.Device devices = 1;
    repeated .plcnet.api.GetNetworkOverview.DataRate data_rates = 2;
  }
  .plcnet.api.GetNetworkOverview.LogicalNetwork network = 1;
}
```

**Comment by Shutgun** [comment]
We only have the *_pb2.py-files, because that is exactly what we asked for.  But I already forwarded your request to devolo's Director Software and expect an answer in the first week of January.

**Comment by gebi** [comment]
awesome, thx!

that means devolo already handed you over the full proto files ;)
just for reference if anyone needs the raw proto file, they can be extracted via calling `GetDebugString()` on the `FileDescriptor` structure like:

```
> import devolo_plc_api
> print(devolo_plc_api.plcnet_api.getnetworkoverview_pb2.DESCRIPTOR.GetDebugString())
syntax = "proto3";
...
```

ps.: you'd actually need the latest python protobuf lib because python just got the `GetDebugString()` interface that java/c++ had since ages

pps: in the meantime i've extracted all proto files from the published src files and they seem to work fine for go, though i hoped to find syslog and tr069 config settings in there, to no avail.
